### ISSUE TITLE
Need to understand Discourse API data response

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/discourse-reader#1]
Data response from Discourse data needs to be understood better so @rohanbansal12 can create the data model for
1. `category` - this is the top level of the forum. For example `Diamond DAO`
2. `posts` - need to understand when the post was made
3. `user` - which posts did a user post

@Xqua can you assist @rohanbansal12 in understanding the data model at all?

**Comment by rohanbansal12** [comment]
This code now makes sense and we have somewhat of a logical structure. I will refactor the code slightly to improve readability.
