### ISSUE TITLE
Initial DB Schema

### ISSUE THREAD

**Issue by rohanbansal12** [DiamondDAO/discourse-reader#2]
## Category/Guild

- category_id
- name
- slug
- topic_count
- post_count
- position
- description
- description_text
- description_excerpt
- topic_url
- read_restricted
- notification_level
- has_children
- num_featured_topics
- minimum_required_tags
- topics_day
- topics_week
- topics_month
- topics_year
- topics_all_time
- uploaded_logo
- uploaded_background

## Topic

- topic_id
- category_id
- title
- fancy_title
- slug
- posts_count
- reply_count
- image_url
- created_at
- bumped
- bumped_at
- archetype
- unseen
- pinned
- excerpt
- visible
- closed
- archived
- bookmarked
- liked
- tags
- views
- like_count
- has_summary
- pinned_globally
- featured_link

## Posts

- post_id
- topic_id
- user_id
- name
- username
- created_at
- cooked
- post_number
- post_type
- updated_at
- reply_count
- reply_to_post_number
- quote_count
- incoming_link_number
- reads
- readers_count
- score
- read
- bookmarked
- admin
- staff
- hidden
- deleted_at
- user_deleted
- edit_reason
- like_count

## User

- user_id
- username
- name
- time_read
- likes_received
- likes_given
- topics_entered
- topic_count
- post_count
- posts_read
- days_visited
- avatar_template
- title
- ethUser

**Comment by rohanbansal12** [comment]
I need to revise for likes. The raw scraping seems to be giving us some issues with likes structuring

**Comment by clemp** [comment]
@rohanbansal12 If it's complicated to structure for "likes" at the moment, then make a note and move on without for the demo scope.

**Comment by rohanbansal12** [comment]
Currently we are getting like counts for each post. Eventually, we will be able to create a separate likes table as well.
